<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <ItemGroup>
    <ProjectReference Include="..\src\OroQuizClash.Api\OroQuizClash.Api.csproj" />
    <ProjectReference Include="..\src\Admin\QuizArena.Admin\QuizArena.Admin.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" />
    <PackageReference Include="Aspire.Hosting.Redis" />
    <PackageReference Include="Aspire.Hosting.SqlServer" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>8038f097-19b4-4eee-992c-cb44b780c9f0</UserSecretsId>
    <NoWarn>$(NoWarn);ASPIRECERTIFICATES001</NoWarn>
  </PropertyGroup>

</Project>
